apiVersion: v1
kind: Pod
metadata:
  name: random-number-generator
spec:
  containers:
    - image: alpine
      name: rng
      command: ["/bin/sh","-c","shuf -i 0-500 -n 1 >> /opt/output.log && sleep 120"]
      volumeMounts:
      - name: log-storage
        mountPath: /opt
  volumes:
    - name: log-storage
      hostPath:
        path: /data
        type: DirectoryOrCreate

