apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-demo
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: pod-for-rs-demo
    spec:
      containers:
      - image: nginx
        name: nginx
  selector:
    matchLabels:
      app: pod-for-rs-demo
