apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  completions: 4
  template:
    metadata:
    spec:
      containers:
      - image: busybox
        name: pi
        command:
        - echo
        - Hello World
      restartPolicy: Never


