apiVersion: batch/v1beta1
kind: CronJob
metadata:
  creationTimestamp: null
  name: cj
spec:
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: cj
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - command:
            - echo
            - Hello World
            image: busybox
            name: cj
            resources: {}
          restartPolicy: OnFailure
  schedule: '* * * * *'
status: {}
