apiVersion: v1
kind: Pod
metadata:
  name: config-map-volume 
spec:
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
    - name: customwebcontent
      mountPath: /usr/share/nginx/html
  volumes:
  - name: customwebcontent
    configMap:
      name: html-content
      items:
      - key: webcontent.html
        path: index.html

