apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: csr-for-alice
spec: 
  groups:
  - system:authenticated
  usages: 
  - digital signature
  - key encipherment
  - client auth
  signerName: kubernetes.io/kube-apiserver-client  
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1ZUQ0NBVDBDQVFBd0VERU9NQXdHQTFVRUF3d0ZZV3hwWTJVd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQQpBNElCRHdBd2dnRUtBb0lCQVFESlZ6U1pGU21TREljUm1VRDZTZk8xbDFjb2FEYkZpWUxYNWJCeWpLOGdVOUlFClc5ZVcvWnpuMC9Ibi9NbklkQnZuaGhsU3hUdW1kYncyS3hrVytIVGZuS1U2aFdxNk5YNWN5MjVobTZqVFZJMDQKRW9sR3NVeFBva2UraGsvS3pRUjBmS3dTVzFWazRoL1NjazdrYjlmdjdVT0lxajJhYU5VVEExUlQ0ZzMraTJmNgpudGVzL052KzhCTlRnNStuMVBPNGJjSUxsTEN3ZkpJT1lvaGdXWEliQjJBb0hBbnNsbXVmMTZqaThjR2l6ZDluCkhqdWUrck5Pd1RJZTlEdzAzWkdOYnYzWDh2eGVvSmtIM0p4QkV0U3h4a0U1R2xNTHRWZ2IyWFFyN0ZzZGNoU2QKa29CRmtBZ2cwcDA0aGJFTllDbnN6TUpOVythYkhUYzFweGhQby83VEFnTUJBQUdnQURBTkJna3Foa2lHOXcwQgpBUXNGQUFPQ0FRRUFWZGlPd0N4NnJUbmFsbno3bXVuaVMzejVNT3hIYm8rcDJYU1I4eTlCdTFKVGxkYzdGNFc1CjIzQUJTSFBRQ2t2Z3A5TEs1aTc3UTRzZTdKQUtKb1pOcnFVZ3hjd1p6QVdqUWNCWFRYTWlXN1VXMkZBaVB6Y0YKenIzcXdUWThQMmNSZVZUY3FmcWhXYWVwTlVmNkZSMURwWkFmQ0EyR0RQMkdyQ1R5WWVmc2RXYStIVkZBeHROTgpkbkRrNHhpWjYycS9rSWo2QWJKeE1BVThVd1ZvQ3F0YnQ2SEw2blZ0R0REbnlwK3dWOC9XQ1BZWnBEWC9Cb3pUCjZrWVFjT012NUhPQUhVWklwOTFxdzhKMGp5K2hGN2RWVnpITUt1ellBYTQzL1ZJcDB2MEhuaW56TktFd2d3d2oKTEhreWVrZ1BvYnZ4TUdOTUc0WmdIYmVUMU1Sa1BrMkNoUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
