apiVersion: v1
kind: Pod
metadata:
  name: toleration
spec:
  containers:
  - image: nginx
    name: nginx
  tolerations:
  - key: exclusiveNode
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"
